spring.application.name=greenit

spring.datasource.url=jdbc:postgresql://localhost:5432/greenit
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

telegram.bot.token=8727910053:AAF8vVNNezQXCM_QM2IbmPRxIBufX52gB_M
telegram.bot.username=greenit_price_bot