spring.config.import=optional:application-local.properties
spring.application.name=greenit

spring.datasource.url=jdbc:postgresql://localhost:5432/greenit


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


telegram.bot.username=greenit_price_bot